name: "Vinotec PHP App"
description: "PHP-Anwendung mit SQLite-Unterstützung"
version: "1.0.0"
slug: "vinotec-php"
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  8080/tcp: 8080
webui: "http://[HOST]:[PORT:8080]/vinotec/"
map:
  - share:rw
  - config:rw
options:
  log_level: info
schema:
  log_level: match(^(trace|debug|info|notice|warning|error|fatal)$)
